# A CI job to build docs from the master branch

name: Build Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
      
    # Runs a set of commands using the runners shell
    - name: Build documentation
      run: |
        chmod +x ./ci/publish_docs.sh
        ./ci/publish_docs.sh

    - name: Push documentation
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: docs/_build/html

